FROM node:20-alpine

RUN mkdir -p /app
WORKDIR /app

# 환경 변수 값 설정
ARG SERVER_PORT
ARG DB_HOST
ARG DB_PORT
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_NAME
ARG DB_SYNC
ARG PASSWORD_HASH_ROUNDS
ARG JWT_SECRET
ARG TOUR_API_KEY
ARG YOUR_EMAIL
ARG YOUR_APP_PASSWORD
ARG DB_PLACE_HOST
ARG DB_PLACE_PORT
ARG DB_PLACE_USERNAME
ARG DB_PLACE_PASSWORD
ARG DB_PLACE_NAME
ARG DB_PLACE_SYNC
ARG CLOUDFLARE_IMG
ARG CLOUDFLARE_API
ARG ELASTICSEARCH_NODE
ARG DISCORD_WEBHOOK_URL
ARG REDIS_USERNAME
ARG REDIS_PASSWORD
ARG REDIS_HOST
ARG REDIS_PORT

COPY package.json package-lock.json ./

COPY . .

# .env 파일 생성 및 환경 변수 값 입력
RUN echo "SERVER_PORT=${SERVER_PORT}" > .env
RUN echo "DB_HOST=${DB_HOST}" >> .env
RUN echo "DB_PORT=${DB_PORT}" >> .env
RUN echo "DB_USERNAME=${DB_USERNAME}" >> .env
RUN echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
RUN echo "DB_NAME=${DB_NAME}" >> .env
RUN echo "DB_SYNC=${DB_SYNC}" >> .env
RUN echo "PASSWORD_HASH_ROUNDS=${PASSWORD_HASH_ROUNDS}" >> .env
RUN echo "JWT_SECRET=${JWT_SECRET}" >> .env
RUN echo "TOUR_API_KEY=${TOUR_API_KEY}" >> .env
RUN echo "YOUR_EMAIL=${YOUR_EMAIL}" >> .env
RUN echo "YOUR_APP_PASSWORD=${YOUR_APP_PASSWORD}" >> .env
RUN echo "DB_PLACE_HOST=${DB_PLACE_HOST}" >> .env
RUN echo "DB_PLACE_PORT=${DB_PLACE_PORT}" >> .env
RUN echo "DB_PLACE_USERNAME=${DB_PLACE_USERNAME}" >> .env
RUN echo "DB_PLACE_PASSWORD=${DB_PLACE_PASSWORD}" >> .env
RUN echo "DB_PLACE_NAME=${DB_PLACE_NAME}" >> .env
RUN echo "DB_PLACE_SYNC=${DB_PLACE_SYNC}" >> .env
RUN echo "CLOUDFLARE_IMG=${CLOUDFLARE_IMG}" >> .env
RUN echo "CLOUDFLARE_API=${CLOUDFLARE_API}" >> .env
RUN echo "ELASTICSEARCH_NODE=${ELASTICSEARCH_NODE}" >> .env
RUN echo "DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}" >> .env
RUN echo "REDIS_USERNAME=${REDIS_USERNAME}" >> .env
RUN echo "REDIS_PASSWORD=${REDIS_PASSWORD}" >> .env
RUN echo "REDIS_HOST=${REDIS_HOST}" >> .env
RUN echo "REDIS_PORT=${REDIS_PORT}" >> .env


RUN npm ci

RUN npm run build

CMD ["node", "dist/main"]