@domain = http://localhost:3000/api
@accessToken = {{loginToken.response.body.data.accessToken}}

###로그인 - 완료
# @name loginToken
POST  {{domain}}/auth/login
Content-Type: application/json

{
  "email":"hmalbebe@hal.be",
  "password":"halbebe"
}


###로그인 - 완료
POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email":"example@email.com",
  "password":"123123"
}

###로그인 - 완료
POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email":"halmeme@hal.me",
  "password":"123123"
}

###아티클 생성 - 인섬니아 등에서 테스트 요
POST  {{domain}}/article/posting
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "articleTitle": "경주로 가는 여행",
  "editorContent": "글을 쓸 수 있나용"
}

###아티클 상세보기
GET   {{domain}}/article/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}


###내가 쓴 아티클 보기
GET   {{domain}}/article/my-post
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###포스트 전체 보기
GET   {{domain}}/article
Content-Type: application/json
Authorization: Bearer {{accessToken}}


###아티클 좋아요
POST {{domain}}/like/3
Content-Type: application/json
Authorization: Bearer {{accessToken}}


###아티클 좋아요 취소
DELETE {{domain}}/like/3
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###아티클 댓글 생성
POST {{domain}}/comment/3
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "comment": "포항항 ꉂꉂ(ᵔᗜᵔ*)포항항 ꉂꉂ(ᵔᗜᵔ*)"
}

###아티클 댓글 조회
GET  {{domain}}/comment/3
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### 댓글 수정
PATCH {{domain}}/comment/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "comment": "사실 동생이야."
}

### 댓글 삭제
DELETE {{domain}}/comment/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}